import React from 'react'
import Squarer, { Square, Squareb,Squarey,Squareg } from './Square'
import Square1r, { Square1,Square1y,Square1g,Square1b } from './Square1'
import Square2r, { Square2,Square2b, Square2g, Square2y } from './Square2'


const Activities = () => {
  return (
    <div className="container-fluid row row_style ">
      <table>
        <tr>
          <td className="table">
          <h1>Activities</h1>
            <p>
              <b>A small description about the activities </b><br/>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit Interger tristique pellentesque dignissi. Nam eget molestie tortor. Ut at placerat ex Suspendisse potenti.
             </p>
          </td>
          <td>
            <table>
              <tr>
                <td></td>
                <td><Square><img src="../images/download.jpg" /></Square></td>
                <td><Square><button type="button">button</button></Square></td>
                <td><Square/></td>
                <td>
                  <table>
                    <tr>
                      <td>
                      <table>
                          <tr>
                            <td><Square2/></td>
                          </tr>
                          <tr>
                            <td><Square2g/></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                    <tr>
                      <td><Square1r/></td>
                      <td>
                      <table>
                          <tr>
                            <td></td>
                            <td><Square2b/></td>
                          </tr>
                          <tr>
                            <td><Square2g/></td>
                            <td><Square2y/></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>
                <td><Squareg/></td>
                <td>
                  <table>
                    <tr>
                    <td><Square1r/></td>
                      <td>
                        <table>
                          <tr>
                            <td><Square2y/></td>
                          </tr>
                          <tr>
                            <td><Square2b/></td>
                            <td><Square2g/></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                    <tr>
                      <td><Square1b/></td>
                      <td>
                      <table>
                          <tr>
                            <td><Square2g/></td>
                            <td><Square2y/></td>
                          </tr>
                          <tr>
                            <td><Square2r/></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>  
              </tr>
              <tr>
                <td><Square/></td>
                <td><Square/></td>
                <td><Square/></td>
                <td>
                  <table>
                    <tr>
                      <td></td>
                      <td>
                      <table>
                          <tr>
                            <td></td>
                            <td><Square2y/></td>
                          </tr>
                          <tr>
                            <td><Square2b/></td>
                            <td><Square2g/></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                    <tr>
                      <td><Square1g/></td>
                      <td><Square1r/></td>
                    </tr>
                  </table>
                </td>
                <td><Squareb/></td>
                <td><Squarer/></td>
                <td><Squareg/></td>  
              </tr>
              <tr>
                <td><Square/></td>
                <td><Square/></td>
                <td>
                <table>
                    <tr>
                      <td></td>
                      <td>
                      <table>
                          <tr>
                            <td></td>
                            <td><Square2b/></td>
                          </tr>
                          <tr>
                            <td><Square2y/></td>
                            <td><Square2r/></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                    <tr>
                      <td><Square1r/></td>
                      <td><Square1g/></td>
                    </tr>
                  </table>
                </td>
                <td><Squarey/></td>
                <td><Squareg/></td>
                <td><Squareb/></td>
                <td><Squarer/></td>  
              </tr>
              <tr>
                <td>
                  <table>
                    <tr>
                      <td><Square1/></td>
                      <td></td>
                    </tr>
                    <tr>
                      <td></td>
                      <td>
                        <table>
                          <tr>
                            <td></td>
                            <td><Square2g/></td>
                          </tr>
                          <tr>
                            <td><Square2y/></td>
                            <td><Square2b/></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>
                <td>
                  <table>
                    <tr>
                      <td><Square1r/></td>
                      <td>
                      <table>
                          <tr>
                            <td><Square2y/></td>
                            <td><Square2g/></td>
                          </tr>
                          <tr>
                            <td><Square2b/></td>
                            <td><Square2r/></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                    <tr>
                      <td><Square1g/></td>
                      <td><Square1y/></td>
                    </tr>
                  </table>
                </td>
                <td><Squareb/></td>
                <td><Squarer/></td>
                <td><Squarey/></td>
                <td><Squareg/></td>
                <td>
                <table>
                  <tr>
                    <td><Square1b/></td>
                    <td><Square1y/></td>
                  </tr>
                  <tr>
                    <td><Square1r/></td>
                    <td>
                    <table>
                          <tr>
                            <td><Square2g/></td>
                            <td><Square2b/></td>
                          </tr>
                          <tr>
                            <td><Square2/></td>
                          </tr>
                        </table>
                    </td>
                  </tr>
                </table>
                </td>  
              </tr>
            </table>
            </td>
        </tr>
      </table>
    </div>
  )
}

export default Activities
